/* A recursive-descent parser generated by peg 0.1.19 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 44
#line 10 "parse.peg"

#if HAVE_CONFIG_H
#   include <config.h>
#endif

#include "net.h"
#include "types.h"
#include "rinetd.h"
#include "parse.h"

#define YY_CTX_LOCAL 1
#define YY_CTX_MEMBERS \
    FILE *fp; \
    int currentLine; \
    int isAuthAllow; \
    char *tmpPort, *bindPort, *connectPort; \
    int tmpProto, bindProto, connectProto; \
    int serverTimeout; \
    int keepalive; \
    char *bindAddress, *connectAddress, *sourceAddress;
#define YY_INPUT(yyctx, buf, result, max_size) \
{ \
    int yyc = fgetc(yyctx->fp); \
    result = (EOF == yyc) ? 0 : (*(buf) = yyc, 1); \
}
#define PARSE_ERROR exit(1);
#define MEMORY_ERROR { \
        logError("could not allocate memory when parsing configuration.\n"); \
        exit(1); \
    }

#if defined __clang__
#pragma clang diagnostic ignored "-Wunused-parameter"
#pragma clang diagnostic ignored "-Wunused-label"
#elif defined __GNUC__
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wunused-label"
#endif


#ifndef YY_MALLOC
#define YY_MALLOC(C, N)		malloc(N)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(C, P, N)	realloc(P, N)
#endif
#ifndef YY_FREE
#define YY_FREE(C, P)		free(P)
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM_R
#define YYPARSEFROM_R	yyparsefrom_r
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YYRELEASE
#define YYRELEASE	yyrelease
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yy->__begin= yy->__pos, 1)
#endif
#ifndef YY_END
#define YY_END		( yy->__end= yy->__pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif
#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_SIZE
#define YY_BUFFER_SIZE 1024
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *yy, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *__buf;
  int       __buflen;
  int       __pos;
  int       __limit;
  char     *__text;
  int       __textlen;
  int       __begin;
  int       __end;
  int       __textmax;
  yythunk  *__thunks;
  int       __thunkslen;
  int       __thunkpos;
  YYSTYPE   __;
  YYSTYPE  *__val;
  YYSTYPE  *__vals;
  int       __valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#ifndef YY_INPUT
#define YY_INPUT(yy, buf, result, max_size)		\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext _yyctx= { 0, 0 };
yycontext *yyctx= &_yyctx;
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#endif

YY_LOCAL(int) yyrefill(yycontext *yy)
{
  int yyn;
  while (yy->__buflen - yy->__pos < 512)
    {
      yy->__buflen *= 2;
      yy->__buf= (char *)YY_REALLOC(yy, yy->__buf, yy->__buflen);
    }
#ifdef YY_CTX_LOCAL
  YY_INPUT(yy, (yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#else
  YY_INPUT((yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#endif
  if (!yyn) return 0;
  yy->__limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *yy)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  ++yy->__pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *yy, int c)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  if ((unsigned char)yy->__buf[yy->__pos] == c)
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *yy, const char *s)
{
  int yysav= yy->__pos;
  while (*s)
    {
      if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
      if (yy->__buf[yy->__pos] != *s)
        {
          yy->__pos= yysav;
          return 0;
        }
      ++s;
      ++yy->__pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *yy, unsigned char *bits)
{
  int c;
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  c= (unsigned char)yy->__buf[yy->__pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *yy, yyaction action, int begin, int end)
{
  while (yy->__thunkpos >= yy->__thunkslen)
    {
      yy->__thunkslen *= 2;
      yy->__thunks= (yythunk *)YY_REALLOC(yy, yy->__thunks, sizeof(yythunk) * yy->__thunkslen);
    }
  yy->__thunks[yy->__thunkpos].begin=  begin;
  yy->__thunks[yy->__thunkpos].end=    end;
  yy->__thunks[yy->__thunkpos].action= action;
  ++yy->__thunkpos;
}

YY_LOCAL(int) yyText(yycontext *yy, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yy->__textlen < (yyleng + 1))
	{
	  yy->__textlen *= 2;
	  yy->__text= (char *)YY_REALLOC(yy, yy->__text, yy->__textlen);
	}
      memcpy(yy->__text, yy->__buf + begin, yyleng);
    }
  yy->__text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *yy, int yythunkpos)
{
  int pos;
  for (pos= yythunkpos;  pos < yy->__thunkpos;  ++pos)
    {
      yythunk *thunk= &yy->__thunks[pos];
      int yyleng= thunk->end ? yyText(yy, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yy->__text));
      thunk->action(yy, yy->__text, yyleng);
    }
  yy->__thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *yy)
{
  if ((yy->__limit -= yy->__pos))
    {
      memmove(yy->__buf, yy->__buf + yy->__pos, yy->__limit);
    }
  yy->__begin -= yy->__pos;
  yy->__end -= yy->__pos;
  yy->__pos= yy->__thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *yy, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(yy, 0);
      yyCommit(yy);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *yy, char *text, int count)
{
  yy->__val += count;
  while (yy->__valslen <= yy->__val - yy->__vals)
    {
      long offset= yy->__val - yy->__vals;
      yy->__valslen *= 2;
      yy->__vals= (YYSTYPE *)YY_REALLOC(yy, yy->__vals, sizeof(YYSTYPE) * yy->__valslen);
      yy->__val= yy->__vals + offset;
    }
}
YY_LOCAL(void) yyPop(yycontext *yy, char *text, int count)   { yy->__val -= count; }
YY_LOCAL(void) yySet(yycontext *yy, char *text, int count)   { yy->__val[count]= yy->__; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yy, yythunkpos0)

YY_RULE(int) yy_eof(yycontext *yy); /* 44 */
YY_RULE(int) yy_id(yycontext *yy); /* 43 */
YY_RULE(int) yy_label(yycontext *yy); /* 42 */
YY_RULE(int) yy_bare_ipv6(yycontext *yy); /* 41 */
YY_RULE(int) yy_digit(yycontext *yy); /* 40 */
YY_RULE(int) yy_hexdigit(yycontext *yy); /* 39 */
YY_RULE(int) yy_hostname(yycontext *yy); /* 38 */
YY_RULE(int) yy_ipv6(yycontext *yy); /* 37 */
YY_RULE(int) yy_ipv4(yycontext *yy); /* 36 */
YY_RULE(int) yy_name(yycontext *yy); /* 35 */
YY_RULE(int) yy_filename(yycontext *yy); /* 34 */
YY_RULE(int) yy_pattern(yycontext *yy); /* 33 */
YY_RULE(int) yy_auth_key(yycontext *yy); /* 32 */
YY_RULE(int) yy_service(yycontext *yy); /* 31 */
YY_RULE(int) yy_proto(yycontext *yy); /* 30 */
YY_RULE(int) yy_port(yycontext *yy); /* 29 */
YY_RULE(int) yy_keepalive_value(yycontext *yy); /* 28 */
YY_RULE(int) yy_number(yycontext *yy); /* 27 */
YY_RULE(int) yy_option_keepalive(yycontext *yy); /* 26 */
YY_RULE(int) yy_option_source(yycontext *yy); /* 25 */
YY_RULE(int) yy_option_timeout(yycontext *yy); /* 24 */
YY_RULE(int) yy_option(yycontext *yy); /* 23 */
YY_RULE(int) yy_option_list(yycontext *yy); /* 22 */
YY_RULE(int) yy_full_port(yycontext *yy); /* 21 */
YY_RULE(int) yy_address(yycontext *yy); /* 20 */
YY_RULE(int) yy_server_options(yycontext *yy); /* 19 */
YY_RULE(int) yy_connect_port(yycontext *yy); /* 18 */
YY_RULE(int) yy_connect_address(yycontext *yy); /* 17 */
YY_RULE(int) yy_bind_port(yycontext *yy); /* 16 */
YY_RULE(int) yy_bind_address(yycontext *yy); /* 15 */
YY_RULE(int) yy_buffersize(yycontext *yy); /* 14 */
YY_RULE(int) yy_logcommon(yycontext *yy); /* 13 */
YY_RULE(int) yy_pidfile(yycontext *yy); /* 12 */
YY_RULE(int) yy_logfile(yycontext *yy); /* 11 */
YY_RULE(int) yy_auth_rule(yycontext *yy); /* 10 */
YY_RULE(int) yy_server_rule(yycontext *yy); /* 9 */
YY_RULE(int) yy_comment(yycontext *yy); /* 8 */
YY_RULE(int) yy_command(yycontext *yy); /* 7 */
YY_RULE(int) yy__(yycontext *yy); /* 6 */
YY_RULE(int) yy_invalid_syntax(yycontext *yy); /* 5 */
YY_RULE(int) yy_eol(yycontext *yy); /* 4 */
YY_RULE(int) yy_line(yycontext *yy); /* 3 */
YY_RULE(int) yy_sol(yycontext *yy); /* 2 */
YY_RULE(int) yy_file(yycontext *yy); /* 1 */

YY_ACTION(void) yy_1_sol(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_sol\n"));
  {
#line 181
   ++yy->currentLine; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_invalid_syntax(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_invalid_syntax\n"));
  {
#line 155
  
    logError("invalid syntax at line %d: %s\n",
            yy->currentLine, yytext);
    PARSE_ERROR; /* FIXME */
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_buffersize(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_buffersize\n"));
  {
#line 145
  
    bufferSize = atoi(yytext);
    if (bufferSize < 1024 || bufferSize > 1048576) {
        logError("invalid buffer size %d at line %d (must be 1024-1048576)\n",
                 bufferSize, yy->currentLine);
        PARSE_ERROR;
    }
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_logcommon(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_logcommon\n"));
  {
#line 140
  
    logFormatCommon = 1;
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_pidfile(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_pidfile\n"));
  {
#line 132
  
    pidLogFileName = strdup(yytext);
    if (!pidLogFileName) {
        MEMORY_ERROR;
    }
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_logfile(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_logfile\n"));
  {
#line 124
  
    logFileName = strdup(yytext);
    if (!logFileName) {
        MEMORY_ERROR;
    }
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_auth_key(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_auth_key\n"));
  {
#line 121
   yy->isAuthAllow = (yytext[0] == 'a'); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_auth_rule(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_auth_rule\n"));
  {
#line 99
  
    allRules = (Rule *)
        realloc(allRules, sizeof(Rule) * (allRulesCount + 1));
    if (!allRules) {
        MEMORY_ERROR;
    }
    allRules[allRulesCount].pattern = strdup(yytext);
    if (!allRules[allRulesCount].pattern) {
        MEMORY_ERROR;
    }
    allRules[allRulesCount].type = yy->isAuthAllow ? allowRule : denyRule;
    if (seTotal > 0) {
        if (seInfo[seTotal - 1].rulesStart == 0 && seInfo[seTotal - 1].rulesCount == 0) {
            seInfo[seTotal - 1].rulesStart = allRulesCount;
        }
        ++seInfo[seTotal - 1].rulesCount;
    } else {
        ++globalRulesCount;
    }
    ++allRulesCount;
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_proto(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_proto\n"));
  {
#line 96
   yy->tmpProto = IPPROTO_TCP; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_proto(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_proto\n"));
  {
#line 95
   yy->tmpProto = IPPROTO_UDP; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_proto(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_proto\n"));
  {
#line 94
   yy->tmpProto = IPPROTO_TCP; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_port(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_port\n"));
  {
#line 93
   yy->tmpPort = strdup(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_option_keepalive(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_option_keepalive\n"));
  {
#line 87
   yy->keepalive = (yytext[1] == 'n') ? 1 : 0; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_option_source(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_option_source\n"));
  {
#line 86
   yy->sourceAddress = strdup(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_option_timeout(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_option_timeout\n"));
  {
#line 85
   yy->serverTimeout = atoi(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_connect_port(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_connect_port\n"));
  {
#line 80
   yy->connectPort = yy->tmpPort; yy->connectProto = yy->tmpProto; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_bind_port(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_bind_port\n"));
  {
#line 79
   yy->bindPort = yy->tmpPort; yy->bindProto = yy->tmpProto; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_connect_address(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_connect_address\n"));
  {
#line 78
   yy->connectAddress = strdup(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_bind_address(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_bind_address\n"));
  {
#line 77
   yy->bindAddress = strdup(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_server_rule(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_server_rule\n"));
  {
#line 57
  
    /* keepalive: -1 = not set (default to on), 0 = off, 1 = on */
    int keepalive = (yy->keepalive == -1) ? 1 : yy->keepalive;

    addServer(yy->bindAddress, yy->bindPort, yy->bindProto,
        yy->connectAddress, yy->connectPort, yy->connectProto,
        yy->serverTimeout > 0 ? yy->serverTimeout : RINETD_DEFAULT_UDP_TIMEOUT,
        yy->sourceAddress,
        keepalive);
    free(yy->bindAddress);
    free(yy->connectAddress);
    free(yy->sourceAddress);
    yy->bindAddress = yy->connectAddress = yy->sourceAddress = NULL;
    free(yy->bindPort);
    free(yy->connectPort);
    yy->bindPort = yy->connectPort = NULL;
    yy->serverTimeout = 0;
    yy->keepalive = -1;
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}

YY_RULE(int) yy_eof(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "eof"));  if (!yymatchChar(yy, '\0')) goto l1;
  yyprintf((stderr, "  ok   %s @ %s\n", "eof", yy->__buf+yy->__pos));
  return 1;
  l1:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eof", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_id(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "id"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l2;
  yyprintf((stderr, "  ok   %s @ %s\n", "id", yy->__buf+yy->__pos));
  return 1;
  l2:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "id", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_label(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "label"));
  {  int yypos4= yy->__pos, yythunkpos4= yy->__thunkpos;  if (!yy_id(yy)) goto l5;  goto l4;
  l5:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yy_digit(yy)) goto l3;
  }
  l4:;	
  l6:;	
  {  int yypos7= yy->__pos, yythunkpos7= yy->__thunkpos;
  {  int yypos8= yy->__pos, yythunkpos8= yy->__thunkpos;  if (!yymatchChar(yy, '-')) goto l9;  goto l8;
  l9:;	  yy->__pos= yypos8; yy->__thunkpos= yythunkpos8;  if (!yy_id(yy)) goto l10;  goto l8;
  l10:;	  yy->__pos= yypos8; yy->__thunkpos= yythunkpos8;  if (!yy_digit(yy)) goto l7;
  }
  l8:;	  goto l6;
  l7:;	  yy->__pos= yypos7; yy->__thunkpos= yythunkpos7;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "label", yy->__buf+yy->__pos));
  return 1;
  l3:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "label", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_bare_ipv6(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "bare_ipv6"));
  l12:;	
  {  int yypos13= yy->__pos, yythunkpos13= yy->__thunkpos;  if (!yy_hexdigit(yy)) goto l13;  goto l12;
  l13:;	  yy->__pos= yypos13; yy->__thunkpos= yythunkpos13;
  }  if (!yymatchChar(yy, ':')) goto l11;
  l14:;	
  {  int yypos15= yy->__pos, yythunkpos15= yy->__thunkpos;
  {  int yypos16= yy->__pos, yythunkpos16= yy->__thunkpos;  if (!yy_hexdigit(yy)) goto l17;  goto l16;
  l17:;	  yy->__pos= yypos16; yy->__thunkpos= yythunkpos16;  if (!yymatchChar(yy, ':')) goto l15;
  }
  l16:;	  goto l14;
  l15:;	  yy->__pos= yypos15; yy->__thunkpos= yythunkpos15;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "bare_ipv6", yy->__buf+yy->__pos));
  return 1;
  l11:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bare_ipv6", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_digit(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "digit"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l18;
  yyprintf((stderr, "  ok   %s @ %s\n", "digit", yy->__buf+yy->__pos));
  return 1;
  l18:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "digit", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_hexdigit(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "hexdigit"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\176\000\000\000\176\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l19;
  yyprintf((stderr, "  ok   %s @ %s\n", "hexdigit", yy->__buf+yy->__pos));
  return 1;
  l19:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "hexdigit", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_hostname(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "hostname"));
  l21:;	
  {  int yypos22= yy->__pos, yythunkpos22= yy->__thunkpos;  if (!yy_label(yy)) goto l22;  if (!yymatchChar(yy, '.')) goto l22;  goto l21;
  l22:;	  yy->__pos= yypos22; yy->__thunkpos= yythunkpos22;
  }  if (!yy_name(yy)) goto l20;
  {  int yypos23= yy->__pos, yythunkpos23= yy->__thunkpos;  if (!yymatchChar(yy, '.')) goto l23;  goto l24;
  l23:;	  yy->__pos= yypos23; yy->__thunkpos= yythunkpos23;
  }
  l24:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "hostname", yy->__buf+yy->__pos));
  return 1;
  l20:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "hostname", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ipv6(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ipv6"));
  {  int yypos26= yy->__pos, yythunkpos26= yy->__thunkpos;  if (!yymatchChar(yy, '[')) goto l27;  if (!yy_bare_ipv6(yy)) goto l27;  if (!yymatchChar(yy, ']')) goto l27;  goto l26;
  l27:;	  yy->__pos= yypos26; yy->__thunkpos= yythunkpos26;  if (!yy_bare_ipv6(yy)) goto l25;
  }
  l26:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "ipv6", yy->__buf+yy->__pos));
  return 1;
  l25:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ipv6", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ipv4(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ipv4"));
  {  int yypos29= yy->__pos, yythunkpos29= yy->__thunkpos;  if (!yy_number(yy)) goto l30;  if (!yymatchChar(yy, '.')) goto l30;  if (!yy_number(yy)) goto l30;  if (!yymatchChar(yy, '.')) goto l30;  if (!yy_number(yy)) goto l30;  if (!yymatchChar(yy, '.')) goto l30;  if (!yy_number(yy)) goto l30;  goto l29;
  l30:;	  yy->__pos= yypos29; yy->__thunkpos= yythunkpos29;  if (!yymatchChar(yy, '0')) goto l28;
  }
  l29:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "ipv4", yy->__buf+yy->__pos));
  return 1;
  l28:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ipv4", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_name(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "name"));  if (!yy_id(yy)) goto l31;
  l32:;	
  {  int yypos33= yy->__pos, yythunkpos33= yy->__thunkpos;
  {  int yypos34= yy->__pos, yythunkpos34= yy->__thunkpos;  if (!yymatchChar(yy, '-')) goto l35;  goto l34;
  l35:;	  yy->__pos= yypos34; yy->__thunkpos= yythunkpos34;  if (!yy_id(yy)) goto l36;  goto l34;
  l36:;	  yy->__pos= yypos34; yy->__thunkpos= yythunkpos34;  if (!yy_digit(yy)) goto l33;
  }
  l34:;	  goto l32;
  l33:;	  yy->__pos= yypos33; yy->__thunkpos= yythunkpos33;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "name", yy->__buf+yy->__pos));
  return 1;
  l31:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "name", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_filename(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "filename"));
  {  int yypos38= yy->__pos, yythunkpos38= yy->__thunkpos;  if (!yymatchChar(yy, '"')) goto l39;  if (!yymatchClass(yy, (unsigned char *)"\377\377\377\377\373\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l39;
  l40:;	
  {  int yypos41= yy->__pos, yythunkpos41= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\377\377\377\377\373\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l41;  goto l40;
  l41:;	  yy->__pos= yypos41; yy->__thunkpos= yythunkpos41;
  }  if (!yymatchChar(yy, '"')) goto l39;  goto l38;
  l39:;	  yy->__pos= yypos38; yy->__thunkpos= yythunkpos38;  if (!yymatchClass(yy, (unsigned char *)"\377\331\377\377\376\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l37;
  l42:;	
  {  int yypos43= yy->__pos, yythunkpos43= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\377\331\377\377\376\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l43;  goto l42;
  l43:;	  yy->__pos= yypos43; yy->__thunkpos= yythunkpos43;
  }
  }
  l38:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "filename", yy->__buf+yy->__pos));
  return 1;
  l37:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "filename", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_pattern(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "pattern"));
  {  int yypos47= yy->__pos, yythunkpos47= yy->__thunkpos;  if (!yy_hexdigit(yy)) goto l48;  goto l47;
  l48:;	  yy->__pos= yypos47; yy->__thunkpos= yythunkpos47;  if (!yymatchChar(yy, '[')) goto l49;  goto l47;
  l49:;	  yy->__pos= yypos47; yy->__thunkpos= yythunkpos47;  if (!yymatchChar(yy, ']')) goto l50;  goto l47;
  l50:;	  yy->__pos= yypos47; yy->__thunkpos= yythunkpos47;  if (!yymatchChar(yy, ':')) goto l51;  goto l47;
  l51:;	  yy->__pos= yypos47; yy->__thunkpos= yythunkpos47;  if (!yymatchChar(yy, '.')) goto l52;  goto l47;
  l52:;	  yy->__pos= yypos47; yy->__thunkpos= yythunkpos47;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\004\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l44;
  }
  l47:;	
  l45:;	
  {  int yypos46= yy->__pos, yythunkpos46= yy->__thunkpos;
  {  int yypos53= yy->__pos, yythunkpos53= yy->__thunkpos;  if (!yy_hexdigit(yy)) goto l54;  goto l53;
  l54:;	  yy->__pos= yypos53; yy->__thunkpos= yythunkpos53;  if (!yymatchChar(yy, '[')) goto l55;  goto l53;
  l55:;	  yy->__pos= yypos53; yy->__thunkpos= yythunkpos53;  if (!yymatchChar(yy, ']')) goto l56;  goto l53;
  l56:;	  yy->__pos= yypos53; yy->__thunkpos= yythunkpos53;  if (!yymatchChar(yy, ':')) goto l57;  goto l53;
  l57:;	  yy->__pos= yypos53; yy->__thunkpos= yythunkpos53;  if (!yymatchChar(yy, '.')) goto l58;  goto l53;
  l58:;	  yy->__pos= yypos53; yy->__thunkpos= yythunkpos53;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\004\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l46;
  }
  l53:;	  goto l45;
  l46:;	  yy->__pos= yypos46; yy->__thunkpos= yythunkpos46;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "pattern", yy->__buf+yy->__pos));
  return 1;
  l44:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pattern", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_auth_key(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "auth_key"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l59;
#undef yytext
#undef yyleng
  }
  {  int yypos60= yy->__pos, yythunkpos60= yy->__thunkpos;  if (!yymatchString(yy, "allow")) goto l61;  goto l60;
  l61:;	  yy->__pos= yypos60; yy->__thunkpos= yythunkpos60;  if (!yymatchString(yy, "deny")) goto l59;
  }
  l60:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l59;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_auth_key, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "auth_key", yy->__buf+yy->__pos));
  return 1;
  l59:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "auth_key", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_service(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "service"));  if (!yy_name(yy)) goto l62;
  yyprintf((stderr, "  ok   %s @ %s\n", "service", yy->__buf+yy->__pos));
  return 1;
  l62:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "service", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_proto(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "proto"));
  {  int yypos64= yy->__pos, yythunkpos64= yy->__thunkpos;  if (!yymatchString(yy, "/tcp")) goto l65;  yyDo(yy, yy_1_proto, yy->__begin, yy->__end);  goto l64;
  l65:;	  yy->__pos= yypos64; yy->__thunkpos= yythunkpos64;  if (!yymatchString(yy, "/udp")) goto l66;  yyDo(yy, yy_2_proto, yy->__begin, yy->__end);  goto l64;
  l66:;	  yy->__pos= yypos64; yy->__thunkpos= yythunkpos64;  if (!yymatchString(yy, "")) goto l63;  yyDo(yy, yy_3_proto, yy->__begin, yy->__end);
  }
  l64:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "proto", yy->__buf+yy->__pos));
  return 1;
  l63:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "proto", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_port(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "port"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l67;
#undef yytext
#undef yyleng
  }
  {  int yypos68= yy->__pos, yythunkpos68= yy->__thunkpos;  if (!yy_number(yy)) goto l69;  goto l68;
  l69:;	  yy->__pos= yypos68; yy->__thunkpos= yythunkpos68;  if (!yy_service(yy)) goto l67;
  }
  l68:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l67;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_port, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "port", yy->__buf+yy->__pos));
  return 1;
  l67:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "port", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_keepalive_value(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "keepalive_value"));
  {  int yypos71= yy->__pos, yythunkpos71= yy->__thunkpos;  if (!yymatchString(yy, "on")) goto l72;  goto l71;
  l72:;	  yy->__pos= yypos71; yy->__thunkpos= yythunkpos71;  if (!yymatchString(yy, "off")) goto l70;
  }
  l71:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "keepalive_value", yy->__buf+yy->__pos));
  return 1;
  l70:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "keepalive_value", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_number(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "number"));  if (!yy_digit(yy)) goto l73;
  l74:;	
  {  int yypos75= yy->__pos, yythunkpos75= yy->__thunkpos;  if (!yy_digit(yy)) goto l75;  goto l74;
  l75:;	  yy->__pos= yypos75; yy->__thunkpos= yythunkpos75;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "number", yy->__buf+yy->__pos));
  return 1;
  l73:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "number", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_option_keepalive(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "option_keepalive"));  if (!yymatchString(yy, "keepalive")) goto l76;
  {  int yypos77= yy->__pos, yythunkpos77= yy->__thunkpos;  if (!yy__(yy)) goto l77;  goto l78;
  l77:;	  yy->__pos= yypos77; yy->__thunkpos= yythunkpos77;
  }
  l78:;	  if (!yymatchChar(yy, '=')) goto l76;
  {  int yypos79= yy->__pos, yythunkpos79= yy->__thunkpos;  if (!yy__(yy)) goto l79;  goto l80;
  l79:;	  yy->__pos= yypos79; yy->__thunkpos= yythunkpos79;
  }
  l80:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l76;
#undef yytext
#undef yyleng
  }  if (!yy_keepalive_value(yy)) goto l76;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l76;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_option_keepalive, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "option_keepalive", yy->__buf+yy->__pos));
  return 1;
  l76:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "option_keepalive", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_option_source(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "option_source"));  if (!yymatchString(yy, "src")) goto l81;
  {  int yypos82= yy->__pos, yythunkpos82= yy->__thunkpos;  if (!yy__(yy)) goto l82;  goto l83;
  l82:;	  yy->__pos= yypos82; yy->__thunkpos= yythunkpos82;
  }
  l83:;	  if (!yymatchChar(yy, '=')) goto l81;
  {  int yypos84= yy->__pos, yythunkpos84= yy->__thunkpos;  if (!yy__(yy)) goto l84;  goto l85;
  l84:;	  yy->__pos= yypos84; yy->__thunkpos= yythunkpos84;
  }
  l85:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l81;
#undef yytext
#undef yyleng
  }  if (!yy_address(yy)) goto l81;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l81;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_option_source, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "option_source", yy->__buf+yy->__pos));
  return 1;
  l81:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "option_source", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_option_timeout(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "option_timeout"));  if (!yymatchString(yy, "timeout")) goto l86;
  {  int yypos87= yy->__pos, yythunkpos87= yy->__thunkpos;  if (!yy__(yy)) goto l87;  goto l88;
  l87:;	  yy->__pos= yypos87; yy->__thunkpos= yythunkpos87;
  }
  l88:;	  if (!yymatchChar(yy, '=')) goto l86;
  {  int yypos89= yy->__pos, yythunkpos89= yy->__thunkpos;  if (!yy__(yy)) goto l89;  goto l90;
  l89:;	  yy->__pos= yypos89; yy->__thunkpos= yythunkpos89;
  }
  l90:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l86;
#undef yytext
#undef yyleng
  }  if (!yy_number(yy)) goto l86;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l86;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_option_timeout, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "option_timeout", yy->__buf+yy->__pos));
  return 1;
  l86:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "option_timeout", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_option(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "option"));
  {  int yypos92= yy->__pos, yythunkpos92= yy->__thunkpos;  if (!yy_option_timeout(yy)) goto l93;  goto l92;
  l93:;	  yy->__pos= yypos92; yy->__thunkpos= yythunkpos92;  if (!yy_option_source(yy)) goto l94;  goto l92;
  l94:;	  yy->__pos= yypos92; yy->__thunkpos= yythunkpos92;  if (!yy_option_keepalive(yy)) goto l91;
  }
  l92:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "option", yy->__buf+yy->__pos));
  return 1;
  l91:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "option", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_option_list(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "option_list"));  if (!yy_option(yy)) goto l95;
  {  int yypos96= yy->__pos, yythunkpos96= yy->__thunkpos;
  {  int yypos98= yy->__pos, yythunkpos98= yy->__thunkpos;  if (!yy__(yy)) goto l98;  goto l99;
  l98:;	  yy->__pos= yypos98; yy->__thunkpos= yythunkpos98;
  }
  l99:;	  if (!yymatchChar(yy, ',')) goto l96;
  {  int yypos100= yy->__pos, yythunkpos100= yy->__thunkpos;  if (!yy__(yy)) goto l100;  goto l101;
  l100:;	  yy->__pos= yypos100; yy->__thunkpos= yythunkpos100;
  }
  l101:;	  if (!yy_option_list(yy)) goto l96;  goto l97;
  l96:;	  yy->__pos= yypos96; yy->__thunkpos= yythunkpos96;
  }
  l97:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "option_list", yy->__buf+yy->__pos));
  return 1;
  l95:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "option_list", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_full_port(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "full_port"));  if (!yy_port(yy)) goto l102;  if (!yy_proto(yy)) goto l102;
  yyprintf((stderr, "  ok   %s @ %s\n", "full_port", yy->__buf+yy->__pos));
  return 1;
  l102:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "full_port", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_address(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "address"));
  {  int yypos104= yy->__pos, yythunkpos104= yy->__thunkpos;  if (!yy_ipv4(yy)) goto l105;  goto l104;
  l105:;	  yy->__pos= yypos104; yy->__thunkpos= yythunkpos104;  if (!yy_ipv6(yy)) goto l106;  goto l104;
  l106:;	  yy->__pos= yypos104; yy->__thunkpos= yythunkpos104;  if (!yy_hostname(yy)) goto l103;
  }
  l104:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "address", yy->__buf+yy->__pos));
  return 1;
  l103:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "address", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_server_options(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "server_options"));  if (!yymatchChar(yy, '[')) goto l107;
  {  int yypos108= yy->__pos, yythunkpos108= yy->__thunkpos;  if (!yy__(yy)) goto l108;  goto l109;
  l108:;	  yy->__pos= yypos108; yy->__thunkpos= yythunkpos108;
  }
  l109:;	  if (!yy_option_list(yy)) goto l107;
  {  int yypos110= yy->__pos, yythunkpos110= yy->__thunkpos;  if (!yy__(yy)) goto l110;  goto l111;
  l110:;	  yy->__pos= yypos110; yy->__thunkpos= yythunkpos110;
  }
  l111:;	  if (!yymatchChar(yy, ']')) goto l107;
  yyprintf((stderr, "  ok   %s @ %s\n", "server_options", yy->__buf+yy->__pos));
  return 1;
  l107:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "server_options", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_connect_port(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "connect_port"));  if (!yy_full_port(yy)) goto l112;  yyDo(yy, yy_1_connect_port, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "connect_port", yy->__buf+yy->__pos));
  return 1;
  l112:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "connect_port", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_connect_address(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "connect_address"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l113;
#undef yytext
#undef yyleng
  }  if (!yy_address(yy)) goto l113;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l113;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_connect_address, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "connect_address", yy->__buf+yy->__pos));
  return 1;
  l113:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "connect_address", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_bind_port(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "bind_port"));  if (!yy_full_port(yy)) goto l114;  yyDo(yy, yy_1_bind_port, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "bind_port", yy->__buf+yy->__pos));
  return 1;
  l114:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bind_port", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_bind_address(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "bind_address"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l115;
#undef yytext
#undef yyleng
  }  if (!yy_address(yy)) goto l115;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l115;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_bind_address, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "bind_address", yy->__buf+yy->__pos));
  return 1;
  l115:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bind_address", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_buffersize(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "buffersize"));  if (!yymatchString(yy, "buffersize")) goto l116;  if (!yy__(yy)) goto l116;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l116;
#undef yytext
#undef yyleng
  }  if (!yy_number(yy)) goto l116;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l116;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_buffersize, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "buffersize", yy->__buf+yy->__pos));
  return 1;
  l116:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "buffersize", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_logcommon(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "logcommon"));  if (!yymatchString(yy, "logcommon")) goto l117;  yyDo(yy, yy_1_logcommon, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "logcommon", yy->__buf+yy->__pos));
  return 1;
  l117:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "logcommon", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_pidfile(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "pidfile"));  if (!yymatchString(yy, "pidfile")) goto l118;  if (!yy__(yy)) goto l118;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l118;
#undef yytext
#undef yyleng
  }  if (!yy_filename(yy)) goto l118;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l118;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_pidfile, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "pidfile", yy->__buf+yy->__pos));
  return 1;
  l118:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pidfile", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_logfile(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "logfile"));  if (!yymatchString(yy, "logfile")) goto l119;  if (!yy__(yy)) goto l119;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l119;
#undef yytext
#undef yyleng
  }  if (!yy_filename(yy)) goto l119;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l119;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_logfile, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "logfile", yy->__buf+yy->__pos));
  return 1;
  l119:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "logfile", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_auth_rule(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "auth_rule"));  if (!yy_auth_key(yy)) goto l120;  if (!yy__(yy)) goto l120;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l120;
#undef yytext
#undef yyleng
  }  if (!yy_pattern(yy)) goto l120;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l120;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_auth_rule, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "auth_rule", yy->__buf+yy->__pos));
  return 1;
  l120:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "auth_rule", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_server_rule(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "server_rule"));  if (!yy_bind_address(yy)) goto l121;  if (!yy__(yy)) goto l121;  if (!yy_bind_port(yy)) goto l121;  if (!yy__(yy)) goto l121;  if (!yy_connect_address(yy)) goto l121;  if (!yy__(yy)) goto l121;  if (!yy_connect_port(yy)) goto l121;
  {  int yypos122= yy->__pos, yythunkpos122= yy->__thunkpos;
  {  int yypos124= yy->__pos, yythunkpos124= yy->__thunkpos;  if (!yy__(yy)) goto l124;  goto l125;
  l124:;	  yy->__pos= yypos124; yy->__thunkpos= yythunkpos124;
  }
  l125:;	  if (!yy_server_options(yy)) goto l122;  goto l123;
  l122:;	  yy->__pos= yypos122; yy->__thunkpos= yythunkpos122;
  }
  l123:;	  yyDo(yy, yy_1_server_rule, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "server_rule", yy->__buf+yy->__pos));
  return 1;
  l121:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "server_rule", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_comment(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "comment"));  if (!yymatchChar(yy, '#')) goto l126;
  l127:;	
  {  int yypos128= yy->__pos, yythunkpos128= yy->__thunkpos;
  {  int yypos129= yy->__pos, yythunkpos129= yy->__thunkpos;  if (!yy_eol(yy)) goto l129;  goto l128;
  l129:;	  yy->__pos= yypos129; yy->__thunkpos= yythunkpos129;
  }  if (!yymatchDot(yy)) goto l128;  goto l127;
  l128:;	  yy->__pos= yypos128; yy->__thunkpos= yythunkpos128;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "comment", yy->__buf+yy->__pos));
  return 1;
  l126:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "comment", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_command(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "command"));
  {  int yypos131= yy->__pos, yythunkpos131= yy->__thunkpos;  if (!yy_server_rule(yy)) goto l132;  goto l131;
  l132:;	  yy->__pos= yypos131; yy->__thunkpos= yythunkpos131;  if (!yy_auth_rule(yy)) goto l133;  goto l131;
  l133:;	  yy->__pos= yypos131; yy->__thunkpos= yythunkpos131;  if (!yy_logfile(yy)) goto l134;  goto l131;
  l134:;	  yy->__pos= yypos131; yy->__thunkpos= yythunkpos131;  if (!yy_pidfile(yy)) goto l135;  goto l131;
  l135:;	  yy->__pos= yypos131; yy->__thunkpos= yythunkpos131;  if (!yy_logcommon(yy)) goto l136;  goto l131;
  l136:;	  yy->__pos= yypos131; yy->__thunkpos= yythunkpos131;  if (!yy_buffersize(yy)) goto l130;
  }
  l131:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "command", yy->__buf+yy->__pos));
  return 1;
  l130:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "command", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy__(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "_"));  if (!yymatchClass(yy, (unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l137;
  l138:;	
  {  int yypos139= yy->__pos, yythunkpos139= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l139;  goto l138;
  l139:;	  yy->__pos= yypos139; yy->__thunkpos= yythunkpos139;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "_", yy->__buf+yy->__pos));
  return 1;
  l137:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "_", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_invalid_syntax(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "invalid_syntax"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l140;
#undef yytext
#undef yyleng
  }
  {  int yypos143= yy->__pos, yythunkpos143= yy->__thunkpos;  if (!yy_eol(yy)) goto l143;  goto l140;
  l143:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;
  }  if (!yymatchDot(yy)) goto l140;
  l141:;	
  {  int yypos142= yy->__pos, yythunkpos142= yy->__thunkpos;
  {  int yypos144= yy->__pos, yythunkpos144= yy->__thunkpos;  if (!yy_eol(yy)) goto l144;  goto l142;
  l144:;	  yy->__pos= yypos144; yy->__thunkpos= yythunkpos144;
  }  if (!yymatchDot(yy)) goto l142;  goto l141;
  l142:;	  yy->__pos= yypos142; yy->__thunkpos= yythunkpos142;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l140;
#undef yytext
#undef yyleng
  }  if (!yy_eol(yy)) goto l140;  yyDo(yy, yy_1_invalid_syntax, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "invalid_syntax", yy->__buf+yy->__pos));
  return 1;
  l140:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "invalid_syntax", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_eol(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "eol"));
  {  int yypos146= yy->__pos, yythunkpos146= yy->__thunkpos;
  {  int yypos148= yy->__pos, yythunkpos148= yy->__thunkpos;  if (!yymatchChar(yy, '\r')) goto l148;  goto l149;
  l148:;	  yy->__pos= yypos148; yy->__thunkpos= yythunkpos148;
  }
  l149:;	  if (!yymatchChar(yy, '\n')) goto l147;  goto l146;
  l147:;	  yy->__pos= yypos146; yy->__thunkpos= yythunkpos146;  if (!yy_eof(yy)) goto l145;
  }
  l146:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "eol", yy->__buf+yy->__pos));
  return 1;
  l145:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eol", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_line(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "line"));
  {  int yypos151= yy->__pos, yythunkpos151= yy->__thunkpos;  if (!yy__(yy)) goto l151;  goto l152;
  l151:;	  yy->__pos= yypos151; yy->__thunkpos= yythunkpos151;
  }
  l152:;	
  {  int yypos153= yy->__pos, yythunkpos153= yy->__thunkpos;  if (!yy_command(yy)) goto l153;
  {  int yypos155= yy->__pos, yythunkpos155= yy->__thunkpos;  if (!yy__(yy)) goto l155;  goto l156;
  l155:;	  yy->__pos= yypos155; yy->__thunkpos= yythunkpos155;
  }
  l156:;	  goto l154;
  l153:;	  yy->__pos= yypos153; yy->__thunkpos= yythunkpos153;
  }
  l154:;	
  {  int yypos157= yy->__pos, yythunkpos157= yy->__thunkpos;  if (!yy_comment(yy)) goto l157;  goto l158;
  l157:;	  yy->__pos= yypos157; yy->__thunkpos= yythunkpos157;
  }
  l158:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "line", yy->__buf+yy->__pos));
  return 1;
  l150:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "line", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_sol(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "sol"));  yyDo(yy, yy_1_sol, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "sol", yy->__buf+yy->__pos));
  return 1;
  l159:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "sol", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_file(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "file"));
  l161:;	
  {  int yypos162= yy->__pos, yythunkpos162= yy->__thunkpos;  if (!yy_sol(yy)) goto l162;
  {  int yypos163= yy->__pos, yythunkpos163= yy->__thunkpos;  if (!yy_line(yy)) goto l164;  if (!yy_eol(yy)) goto l164;  goto l163;
  l164:;	  yy->__pos= yypos163; yy->__thunkpos= yythunkpos163;  if (!yy_invalid_syntax(yy)) goto l162;
  }
  l163:;	  goto l161;
  l162:;	  yy->__pos= yypos162; yy->__thunkpos= yythunkpos162;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "file", yy->__buf+yy->__pos));
  return 1;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *yy);

YY_PARSE(int) YYPARSEFROM_R(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok, yythunkpos;
  YYSTYPE *yyval;
  if (!yyctx->__buflen)
    {
      yyctx->__buflen= YY_BUFFER_SIZE;
      yyctx->__buf= (char *)YY_MALLOC(yyctx, yyctx->__buflen);
      yyctx->__textlen= YY_BUFFER_SIZE;
      yyctx->__text= (char *)YY_MALLOC(yyctx, yyctx->__textlen);
      yyctx->__thunkslen= YY_STACK_SIZE;
      yyctx->__thunks= (yythunk *)YY_MALLOC(yyctx, sizeof(yythunk) * yyctx->__thunkslen);
      yyctx->__valslen= YY_STACK_SIZE;
      yyctx->__val= yyctx->__vals= (YYSTYPE *)YY_MALLOC(yyctx, sizeof(YYSTYPE) * yyctx->__valslen);
      yyctx->__begin= yyctx->__end= yyctx->__pos= yyctx->__limit= yyctx->__thunkpos= 0;
    }
  yyctx->__begin= yyctx->__end= yyctx->__pos;
  yythunkpos= yyctx->__thunkpos;
  yyval= yyctx->__val;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx, yythunkpos);
  yyctx->__thunkpos= yythunkpos;
  yyctx->__val= yyval;
  return yyok;
}

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  yyctx->__thunkpos= 0;
  yyctx->__val= yyctx->__vals;
  yyok= YYPARSEFROM_R(YY_CTX_ARG_ yystart);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_file);
}

YY_PARSE(yycontext *) YYRELEASE(yycontext *yyctx)
{
  if (yyctx->__buflen)
    {
      yyctx->__buflen= 0;
      YY_FREE(yyctx, yyctx->__buf);
      YY_FREE(yyctx, yyctx->__text);
      YY_FREE(yyctx, yyctx->__thunks);
      YY_FREE(yyctx, yyctx->__vals);
    }
  return yyctx;
}

#endif
#line 185 "parse.peg"


void parseConfiguration(char const *file)
{
    FILE *in = fopen(file, "r");
    if (!in) {
        logError("could not open configuration file %s.\n", file);
        exit(1);
    }

    yycontext ctx;
    memset(&ctx, 0, sizeof(yycontext));
    ctx.fp = in;
    ctx.keepalive = -1;
    if (!yyparse(&ctx)) {
        logError("invalid syntax in file %s, line %d.\n", file, -1);
        exit(1);
    }
    yyrelease(&ctx);

    fclose(in);

    /* Avoid warnings for these unused functions */
    (void)yySet; (void)yyPush; (void)yyPop; (void)yyAccept;
}


